---
title: "Curriculum Vitae"
# sidebar: false
about:
  template: solana
format: html
editor: visual
# css: cv.css
---

## Education

**University of Missouri** [Expected Graduation: 08/2024]{.cvdate} <br> *M.S. in Plant, Insect, and Microbial Sciences* [GPA: 3.92/4.00]{.cvdate}

**University of Minnesota** [Graduated: 05/2017]{.cvdate} <br> *B.S. in Environmental Sciences, Policy, and Management* [GPA: 3.40/4.00]{.cvdate}

## Relevant Experience

**Graduate Research Assistant** [08/2022 - Present]{.cvdate} <br> *University of Missouri - USDA: ARS* [Columbia, MO]{.cvdate} <br> *Thesis Topics: quantitative genetics of soybean, seed composition traits, genome-wide association study, nested association population* <br>

-   Study applied quantitative genetics, gene discovery, and germplasm development of seed composition traits in soybean (Glycine max).
-   Partake in multi-location field trails; select progeny for advancement, clean and package seed, mechanical planting, and manual harvesting to obtain high-quality data for statistical analysis and population advancement.
-   Perform statistical analysis using various software including R, Excel, JMP, SAS and more to interpret results for research and/or publication.
-   Isolate high-quality DNA from leaf tissue and seed samples for subsequent genotyping and analysis of genetic architecture.
-   Train and oversee undergraduate students so that they may work independently to package seed and collect phenotypic measurements via Near-Infrared Spectroscopy (NIRS).

<br> **Independent Contractor** [01/2023- Present]{.cvdate}<br> *Missouri Soybean Association* [Columbia, MO]{.cvdate}<br>

-   Provided subject matter expertise to Missouri Soybean Association to assist with the evaluation of the QSorter Explorer, a high-throughput phenotyping instrument equipped with a 2D/3D camera and NIRS.
-   Determined the accuracy of several calibrations available via the QSorter Explorer by designing experiments, sourcing materials, and analyzing data.
-   Produced written reports, including accuracy statements, to be used in advertisement materials provided to prospective clients. <br>

**Graduate Teaching Assistant** [09/2023 -- 12/2023]{.cvdate} <br> *University of Missouri - Introduction to Plant Breeding* [Columbia, MO]{.cvdate} <br>

-   Collaborated seamlessly with co-teaching assistant to create slides, teach lectures, and grade coursework, providing students with consistent and prompt feedback.
-   Taught lectures as needed on relevant topics such as polyploidy, designing a plant breeding program, germplasm collections, as well as biotic and abiotic stressors.
-   Developed slides to complement the course textbook and promoted student understanding by presenting information to cater to a variety of learning styles.

<br> **Ornamental Horticulturalist** [05/2020 -- 06/2022]{.cvdate} <br> *Countryside Gardens LLC* [Delano, MN]{.cvdate} <br>

-   Actively participated in maintaining a large ornamental plant breeding operation by dividing bare-root stock, taking inventory, maintaining field manifests, phenotyping, maintaining website images and descriptions, posting to social media, and making recommendations for seedling stock selection.
-   Catered to individual needs of over 50 private clients by providing highly detailed and skilled gardening services.
-   Skilled in greenhouse work, consistently maintained hundreds of healthy and vigorous plants under greenhouse conditions through precise watering, pruning, fertilizing, and pest management, maintaining their value as an asset to the company.
-   Audited chemical and hazardous items on the worksite, reviewed safety data sheets (SDS), and ensured all materials were in appropriate secondary containment.

<br> **Scientist 2** [08/2017 -- 04/2020]{.cvdate} <br> **Student Laboratory Technician** [09/2014 - 08/2017]{.cvdate} <br> *University of Minnesota Veterinary Diagnostic Lab - Molecular Diagnostics* [St. Paul, MN]{.cvdate} <br>

-   Wrote and reviewed standard operating procedures (SOPs) for technical, multi-step molecular laboratory procedures to maintain integrity of laboratory procedures across all personnel.
-   Maintained quality control records of all assays performed in the laboratory to ensure assays were falling within acceptable range, ensuring continued certification and funding of the laboratory.
-   Developed and validated clinical assays and workflows to improve service while conserving resources, resulting in saving tens of thousands of dollars.
-   Performed ongoing evaluation of workplace procedures, documents, and results. Documented all non-conforming incidents found during review.
-   Provided accurate and timely clinical testing services to clients by reporting results in LIMS.

<br> **Undergraduate Teaching Assistant** [09/2016 -- 05/2017]{.cvdate} <br> *University of Minnesota - Introduction to Soil Science* [St. Paul, MN]{.cvdate} <br>

-   Educated students on topics pertaining to soil science in a laboratory setting, explored foundational concepts using applied experiments.
-   Collected and utilized student feedback to improve existing coursework by editing laboratory exercises and creating modern graphics, resulting in improved student engagement.

<br> **Undergraduate Research Assistant** [08/2015 -- 09/2015]{.cvdate} <br> *University of Minnesota - Dept. Forest Resources* [St. Paul, MN]{.cvdate} <br>

-   Surveyed vegetative communities of 20 unique sites located at the SPRUCE (Spruce and Peatland Response Under Changing Environments) experimental research station, to determine impact of temperature and carbon dioxide on Northern peatland plant communities.
-   Collected and analyzed data using Microsoft Excel to identify meaningful patterns and relationships between climatic conditions and ecosystem composition. <br>

## Professional Development & Community Outreach

**Mentoring with Mizzou** [01/2023-Present]{.cvdate}<br> *University of Missouri - Office of the Provost* [Columbia, MO]{.cvdate}<br>

-   Participating in research-based, culturally informed mentorship training to improve my capacity and tools for mentoring young colleagues or student workers.
-   Curriculum will address equity and inclusion, ethics, work-life balance, communication skills, and promote independence. <br>

**Graduate Student Association Committee Member** [01/2023-12/2023]{.cvdate}<br> *University of Missouri* <br>

-   Assisted in fostering community among plant science graduate students by hosting bi-annual dinners and creating comprehensive resources for students. <br>

**Hiring Committee Graduate Student Representative** [10/2022-04/2023]{.cvdate} <br> *University of Missouri* <br>

-   Assisted in filling critical position at the Fischer Delta Research Education and Extension Center by reviewing applications, interviewing finalists, and providing recommendations to the division of plant sciences. <br>

**Volunteer** [03/2023]{.cvdate} <br> *Columbia Young Scientists Expo*<br>

-   Judged school-aged students poster presentation for science fair. <br>

**Volunteer** [03/2023-06/2023]{.cvdate} <br> *Cedar Creek Therapeutic Riding Center*<br>

-   Contributed to a safe, healing environment by handling horses and interacting with clients.

## Publications, Presentations & Conferences

**Abstract Talk & Poster Presentation:** 2024 MU Plant Symposium <br> *"Genome-Wide Identification of \>500 Candidate Genes Associated with Amino Acids, Fatty Acids, Trace Elements, and More in Soybean (Glycine max)"* <br>

**Conference:** 2023 American Society of Plant Breeders: Midwest Meeting <br>

**Poster Presentation:** 2023 Soybean Breeders Workship <br> *"Breaking Bottlenecks: Utilizing High-Throughput Robotic Seed Sorting for High Oleic Acid Soybeans"*

## Honors and Awards

Division of Plant Sciences Graduate Student Travel Grant: \$500 [03/2023]{.cvdate}
